[package]
name = "cmake-formatter"
version = "0.1.0"
edition = "2021"

[dependencies]
rowan = "0.16.1"
anyhow = "1.0"
miette = { version = "7.6", features = ["fancy"] }
pretty = "0.12"

[dev-dependencies]
insta = { version = "1.46", features = ["yaml", "glob"] }
rstest = "0.26"
pretty_assertions = "1.4"
