use cmake_fmt::formatter::{
    export_grammars_to_toml, import_grammar_file, FormatConfig, KeywordType,
};
use cmake_fmt::formatter::grammar::{builtin_grammars, config_grammars_to_map};
use std::collections::HashMap;
use tempfile::TempDir;
use std::fs;

#[test]
fn test_export_builtin_grammars_produces_valid_toml() {
    let grammars = builtin_grammars();
    let toml_content = export_grammars_to_toml(&grammars);

    // Should parse back as valid TOML
    let parsed: toml::Value = toml::from_str(&toml_content)
        .expect("Exported TOML should be valid");

    // Check that it has the grammar array
    assert!(parsed.get("grammar").is_some());
    let grammar_array = parsed.get("grammar").unwrap().as_array().unwrap();
    assert!(!grammar_array.is_empty());

    // Import it back and verify
    let imported = import_grammar_file(&toml_content)
        .expect("Should be able to import exported TOML");
    assert!(!imported.is_empty());

    // Check for known commands (simple grammars only, multi-mode skipped in import)
    assert!(imported.contains_key("find_package"));
    assert!(imported.contains_key("target_link_libraries"));
}

#[test]
fn test_export_format_readability() {
    let grammars = builtin_grammars();
    let toml_content = export_grammars_to_toml(&grammars);

    // Check for header comment
    assert!(toml_content.contains("# cmake-fmt grammar export"));
    assert!(toml_content.contains("# Generated by cmake-fmt"));

    // Check for [[grammar]] entries
    assert!(toml_content.contains("[[grammar]]"));

    // Check that keyword types use readable names
    assert!(toml_content.contains("Flag"));
    assert!(toml_content.contains("MultiValue"));
    assert!(toml_content.contains("SingleValue"));

    // Should NOT contain Rust enum syntax
    assert!(!toml_content.contains("KeywordType::"));
}

#[test]
fn test_import_grammar_file() {
    let toml_content = r#"
[[grammar]]
command = "my_custom_command"

[grammar.keywords]
REQUIRED = "Flag"
OUTPUT = "SingleValue"
SOURCES = "MultiValue"
PROPERTIES = "PairValue"
COMMAND = "CommandLine"
"#;

    let imported = import_grammar_file(toml_content)
        .expect("Should parse custom grammar");

    assert!(imported.contains_key("my_custom_command"));
    let grammar = &imported["my_custom_command"];

    assert_eq!(grammar.keyword_type("REQUIRED"), Some(KeywordType::Flag));
    assert_eq!(grammar.keyword_type("OUTPUT"), Some(KeywordType::SingleValue));
    assert_eq!(grammar.keyword_type("SOURCES"), Some(KeywordType::MultiValue));
    assert_eq!(grammar.keyword_type("PROPERTIES"), Some(KeywordType::PairValue));
    assert_eq!(grammar.keyword_type("COMMAND"), Some(KeywordType::CommandLine));
}

#[test]
fn test_import_round_trip() {
    let grammars = builtin_grammars();
    let toml_content = export_grammars_to_toml(&grammars);

    let imported = import_grammar_file(&toml_content)
        .expect("Should import exported TOML");

    // Check that simple grammars round-trip correctly
    // find_package is a simple grammar
    assert!(imported.contains_key("find_package"));
    let find_package = &imported["find_package"];

    // Check that it has expected keywords
    assert_eq!(find_package.keyword_type("REQUIRED"), Some(KeywordType::Flag));
    assert_eq!(find_package.keyword_type("QUIET"), Some(KeywordType::Flag));
    assert_eq!(find_package.keyword_type("COMPONENTS"), Some(KeywordType::MultiValue));

    // target_link_libraries is also simple
    assert!(imported.contains_key("target_link_libraries"));
}

#[test]
fn test_grammar_file_config_loading() {
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let grammar_path = temp_dir.path().join("grammars.toml");

    // Create a custom grammar file
    let grammar_content = r#"
[[grammar]]
command = "my_command"

[grammar.keywords]
FLAG1 = "Flag"
VALUE1 = "SingleValue"
"#;
    fs::write(&grammar_path, grammar_content).expect("Failed to write grammar file");

    // Create a config that references it
    let config_content = format!(
        r#"
indent_width = 2
grammar_files = ["{}"]
"#,
        grammar_path.display()
    );

    // Parse the config
    let config: FormatConfig = toml::from_str(&config_content)
        .expect("Failed to parse config");

    // Check that grammar_files was loaded
    assert_eq!(config.grammar_files.len(), 1);
    assert_eq!(config.grammar_files[0], grammar_path);
}

#[test]
fn test_cli_grammar_file_formatting() {
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let grammar_path = temp_dir.path().join("grammars.toml");

    // Create a custom grammar file
    let grammar_content = r#"
[[grammar]]
command = "my_special_command"

[grammar.keywords]
REQUIRED = "Flag"
FILES = "MultiValue"
"#;
    fs::write(&grammar_path, grammar_content).expect("Failed to write grammar file");

    // Create a config with the grammar file
    let mut config = FormatConfig::default();
    config.grammar_files = vec![grammar_path];

    // Format a CMake file that uses the custom grammar
    let cmake_content = "my_special_command(REQUIRED FILES file1.txt file2.txt)\n";
    let (formatted, _warnings) = cmake_fmt::formatter::format_text_with_diagnostics(
        cmake_content,
        &config,
    );

    // The command should be recognized and formatted
    // At minimum, it should not crash and should produce valid output
    assert!(!formatted.is_empty());
    assert!(formatted.contains("my_special_command"));
}

#[test]
fn test_command_line_keywords_in_config() {
    use cmake_fmt::formatter::CommandGrammarConfig;

    let mut config_grammars = HashMap::new();
    let mut grammar_config = CommandGrammarConfig::default();
    grammar_config.options = vec!["VERBATIM".to_string()];
    grammar_config.command_line_keywords = vec!["COMMAND".to_string()];
    config_grammars.insert("my_command".to_string(), grammar_config);

    let grammar_map = config_grammars_to_map(&config_grammars);

    assert!(grammar_map.contains_key("my_command"));
    let grammar = &grammar_map["my_command"];

    assert_eq!(grammar.keyword_type("VERBATIM"), Some(KeywordType::Flag));
    assert_eq!(grammar.keyword_type("COMMAND"), Some(KeywordType::CommandLine));
}

#[test]
fn test_import_invalid_keyword_type() {
    let toml_content = r#"
[[grammar]]
command = "bad_command"

[grammar.keywords]
BAD_KEYWORD = "InvalidType"
"#;

    let result = import_grammar_file(toml_content);
    assert!(result.is_err());
    assert!(result.unwrap_err().contains("Unknown keyword type"));
}

#[test]
fn test_export_multimode_commands() {
    let grammars = builtin_grammars();
    let toml_content = export_grammars_to_toml(&grammars);

    // install is a multi-mode command
    // Each mode should get its own entry with the mode field set
    let parsed: toml::Value = toml::from_str(&toml_content)
        .expect("Should parse as valid TOML");

    let grammar_array = parsed.get("grammar").unwrap().as_array().unwrap();

    // Find entries for "install" command
    let install_entries: Vec<_> = grammar_array.iter()
        .filter(|entry| {
            entry.get("command")
                .and_then(|c| c.as_str())
                .map(|s| s == "install")
                .unwrap_or(false)
        })
        .collect();

    // Should have multiple entries for install (one per mode)
    assert!(install_entries.len() > 1, "install should have multiple mode entries");

    // At least one should have a mode field
    let has_mode = install_entries.iter().any(|entry| {
        entry.get("mode").is_some()
    });
    assert!(has_mode, "At least one install entry should have a mode field");
}

#[test]
fn test_yaml_import_support() {
    let yaml_content = r#"
grammar:
  - command: test_command
    keywords:
      FLAG1: Flag
      VALUE1: SingleValue
"#;

    let imported = import_grammar_file(yaml_content)
        .expect("Should parse YAML grammar");

    assert!(imported.contains_key("test_command"));
    let grammar = &imported["test_command"];
    assert_eq!(grammar.keyword_type("FLAG1"), Some(KeywordType::Flag));
    assert_eq!(grammar.keyword_type("VALUE1"), Some(KeywordType::SingleValue));
}

#[test]
fn test_grammar_precedence() {
    // Test that precedence is maintained: config > grammar_file > auto-detected
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let grammar_path = temp_dir.path().join("grammars.toml");

    // Create a grammar file that defines a custom command
    let grammar_content = r#"
[[grammar]]
command = "find_package"

[grammar.keywords]
CUSTOM_KEYWORD = "Flag"
"#;
    fs::write(&grammar_path, grammar_content).expect("Failed to write grammar file");

    // Create a config that also defines find_package
    let mut config = FormatConfig::default();
    config.grammar_files = vec![grammar_path];

    let mut grammar_config = cmake_fmt::formatter::CommandGrammarConfig::default();
    grammar_config.options = vec!["CONFIG_KEYWORD".to_string()];
    config.command_grammars.insert("find_package".to_string(), grammar_config);

    // Format with this config - the config grammar should take precedence
    let cmake_content = "find_package(CONFIG_KEYWORD CUSTOM_KEYWORD)\n";
    let (formatted, _warnings) = cmake_fmt::formatter::format_text_with_diagnostics(
        cmake_content,
        &config,
    );

    // Should not crash - precedence is working
    assert!(!formatted.is_empty());
}
